### ISSUE TITLE
unsized single-bit value with question mark not checked 

### ISSUE THREAD

**Issue by astrollo** [MikePopoloski/slang#1149]
According to standard, an unsized single-bit value can be specified as follows: `'0, '1, 'X, 'x, 'Z, 'z`. While the question mark (`?`) character is a SystemVerilog alternative for the `z` character, the standard does not mention its use for unsized single-bit value. 
However, slang does not flag `'?` as an error, even though commercial tools available on edaplayground do report it.
A simple example is the following code, where slang does not report any issue (although it should):
```
module bug(input logic [1:0] a, input logic s, output logic [1:0]y);
assign y = s? a: '?;
endmodule
```

**Comment by MikePopoloski** [comment]
Fixed in 34148f226928f65a83cf2e7cc320d886f1b400d9
