### ISSUE TITLE
Slicing of an expression non flagged as an error

### ISSUE THREAD

**Issue by astrollo** [MikePopoloski/slang#1167]
Simple test code:
```
module signal_wrong (input logic [3:0] a,b, output logic [1:0] c);
assign c = (a & b)[3:2];
endmodule
```
slang does not report any error or warning. However, the code is wrong as reported also by the commercial tools on edaplayground.
slang version 7.0.22+34148f22

**Comment by MikePopoloski** [comment]
Fixed in 1bf41445c7ce49476eeb5d02f40de1e0e051e76e
