### ISSUE TITLE
Commit 5f1163ba breaks docker gcc:7 build

### ISSUE THREAD

**Issue by martinda** [MikePopoloski/slang#167]
Hi,

With `git bisect`, I found that since commit 5f1163ba, I can no longer build in docker gcc:7:
```
docker run --rm -v "$PWD":/usr/src/slang -w /usr/src/slang -ti gcc:7 tools/bin/linux/genie --gcc=linux-gcc gmake
docker run --rm -v "$PWD":/usr/src/slang -w /usr/src/slang -ti gcc:7 make -C build/projects/gmake-linux
```

I get:
```
make: Entering directory '/usr/src/slang/build/projects/gmake-linux'
==== Building slang (debug64) ====
format.cc
/bin/sh: 1: g++-7: not found
slang.make:233: recipe for target '../../linux64_gcc/obj/x64/Debug/slang/external/fmt/format.o' failed
make[1]: *** [../../linux64_gcc/obj/x64/Debug/slang/external/fmt/format.o] Error 127
Makefile:16: recipe for target 'slang' failed
make: *** [slang] Error 2
make: Leaving directory '/usr/src/slang/build/projects/gmake-linux'
```

I am not sure how to fix that since the toolchain.lua script assumes that gcc is installed on the OS with a version suffix.

What do you think?

**Comment by MikePopoloski** [comment]
Yeah, you need to have GCC 7 installed in order to build the code. If for some reason you've installed it without the version suffix but are sure it's actually GCC 7, then feel free to invoke make with the CXX environment flag set to whatever the name of your install is.
