### ISSUE TITLE
How to get code coverage locally

### ISSUE THREAD

**Issue by martinda** [MikePopoloski/slang#178]
Hello Mike,

I would like to learn how to write tests for slang and increase code coverage but I do not know how to get the coverage reports. Can you provide some instructions please? Here is what I did so far:
```bash
export BUILD_TYPE=gcc
docker pull mpopoloski/slang:latest
docker run -itd --name build mpopoloski/slang:latest
docker cp . build:/slang
export ci_env=`bash <(curl -s https://codecov.io/env)`
echo $ci_env 
docker exec $ci_env build slang/scripts/build_gcc.sh
```
I get:
```bash
...
make -j 8
[ 64%] Built target slang
[ 67%] Built target rewriter
[ 70%] Built target depmap
[ 73%] Built target driver
[100%] Built target unittests
ctest
Test project /slang/build
    Start 1: regression_delayed_reg
1/3 Test #1: regression_delayed_reg ...........   Passed    0.00 sec
    Start 2: regression_wire_module
2/3 Test #2: regression_wire_module ...........   Passed    0.00 sec
    Start 3: unittests
3/3 Test #3: unittests ........................   Passed    0.59 sec

100% tests passed, 0 tests failed out of 3

Total Test time (real) =   0.60 sec
cd ..
#bash <(curl -s https://codecov.io/bash) -x 'gcov-8' -a '1> /dev/null 2> /dev/null' || echo 'Codecov failed to upload'
```

How do I generate the coverage files? I had a look at a [travis log output](https://travis-ci.org/MikePopoloski/slang/jobs/472760723), I tried to repeat the same commands inside the docker container, but it's not producing reports.

Can you provide instructions for wanna-be contributors please?

**Comment by MikePopoloski** [comment]
I added some instructions to the wiki here: https://github.com/MikePopoloski/slang/wiki/Build-Reference

Let me know how it turns out.

**Comment by martinda** [comment]
Thank you. I am trying it now. How long does it take for `slang/build/bin/unittests -v normal` to complete? Nothing is printed to the screen. It has been a few hours now.

**Comment by MikePopoloski** [comment]
Should only take seconds to run. Something must be wrong with the setup. I don't usually run with the -v option, I suppose that's from the Catch framework?

**Comment by martinda** [comment]
I got it. Thanks. For the record, here are the steps I used:
```
export BUILD_TYPE=clang
docker pull mpopoloski/slang:latest
docker run -itd --name build mpopoloski/slang:latest
docker cp . build:/slang
export ci_env=`bash <(curl -s https://codecov.io/env)`
docker exec $ci_env build slang/scripts/build_clang.sh
```
The reports are in the container, so I must enter the container:
```
docker exec -ti $ci_env build /bin/bash
```
From, here on, the commands are inside the container:
```
find . -name "*profraw*"
```
It returns:
```
./build/tests/regression/914.profraw
./build/tests/regression/916.profraw
./build/tests/unittests/918.profraw
```
Pick one of the files, say `./build/tests/unittests/918.profraw` and run:
```
llvm-profdata-7 merge -o merged.profdata -sparse ./build/tests/unittests/918.profraw
```
For a line by line coverage report:
```
llvm-cov-7 show build/bin/unittests -instr-profile=merged.profdata
```
