### ISSUE TITLE
Question: missing filesystem, how to setup development environment (docker)

### ISSUE THREAD

**Issue by martinda** [MikePopoloski/slang#183]
I try to setup a development environment for slang, but I cannot get passed this error:
```
/slang/source/../include/slang/text/SourceManager.h:10:10: error: 'filesystem' file not found [clang-diagnostic-error]
#include <filesystem>
         ^
```

How to reproduce:
1. Clone the slang repository, cd into it.
1. Build the image described by this [Dockerfile](https://github.com/martinda/slang/blob/f7b3bc46b22d3de10fa9c51df8c167bebaed8838/Dockerfile#L1) with `docker build --tag slang:dev .`
1. Run it: `docker run -d -v $(pwd):/slang -ti --name slang_dev slang:dev /bin/bash`
1. Exec into the container: `docker exec -ti slang_dev /bin/bash`
1. Build: `scripts/build_clang.sh`

You may need to to erase the `build/` folder before calling `build_clang.sh` as it attempts to create the `build/`folder and fails if it already exists. Then the aforementioned error will occur. Can you please share the description of your development environment or a Dockerfile?

**Comment by MikePopoloski** [comment]
You need an updated libstdc++ for the filesystem library. Installing `g++-8` should get it for you. Alternatively you could probably also tell clang to use libc++ instead.
