### ISSUE TITLE
Add a CMake flag to disable tests

### ISSUE THREAD

**Issue by Kuree** [MikePopoloski/slang#257]
Hello,

I'm using `slang` as a git submodule (using `add_subdirectory`). Is it possible to add a variable/flag in CMake to disable adding all the tests? Thanks.

**Comment by MikePopoloski** [comment]
Sure, I can do that, or I'd welcome a pull request if you want to add it.

I haven't spent any time trying to consume slang as a library via cmake yet, so if you have changes that would make it easier please feel free to propose them.
