### ISSUE TITLE
sv-lang.com website in "Try It Out" doesn't work?

### ISSUE THREAD

**Issue by mithro** [MikePopoloski/slang#263]
The [Try It Out](https://github.com/MikePopoloski/slang/tree/master#try-it-out) section of the README.md links to `sv-lang.com` which appears to be down?

https://github.com/MikePopoloski/slang/blame/master/README.md#L21-L23
```markdown
### Try It Out
Experiment with parsing, type checking, and error detection live [on the web](http://sv-lang.com/) (this tool is inspired by Matt Godbolt's excellent [Compiler Explorer](https://godbolt.org/)). It's still pretty rough but useful for exploring the interactive behavior of the toolchain.
```

**Comment by MikePopoloski** [comment]
It's back up now. I run it off an AWS instance but there's something misconfigured about it and it doesn't always stay up forever. I haven't had time to really look into it.

**Comment by mithro** [comment]
Working for me now! It's pretty cool website.
