### ISSUE TITLE
Add a git tag to first commit so that git-describe works for repo.

### ISSUE THREAD

**Issue by mithro** [MikePopoloski/slang#273]
Could you add a `v0.0` tag to the first commit (849129ede4f90ba31c2c6a546a8450f7eabe2ca7) in this repository? This will make `git-describe` return a useful value for this repository.

```
git tag -a v0.0 849129ede4f90ba31c2c6a546a8450f7eabe2ca7 -m "First commit"
git push origin v0.0
```

**Comment by MikePopoloski** [comment]
Done
