### ISSUE TITLE
Simplify CompilationUnit when producing AST JSON?

### ISSUE THREAD

**Issue by Kuree** [MikePopoloski/slang#296]
Currently `CompilationUnit` is serialized along with elaborated module instances. In most cases the definition in `CompilationUnit` provides the same information as the module instances. Is there any way to simplify the `CompilationUnit` output?

**Comment by MikePopoloski** [comment]
The compilation unit can contain things other than the definition, like parameters or variables or whatever. Also the definition symbol is technically not the same thing as the instances, though they are often very similar.

**Comment by Kuree** [comment]
Got it. Thanks for the explanation.
