### ISSUE TITLE
Support specifying command line options in a separate file

### ISSUE THREAD

**Issue by MikePopoloski** [MikePopoloski/slang#361]

**Comment by krupan** [comment]
Is the psuedo-standard "dot f file" that most simulators support?  If so this is something I would like to help with.

**Comment by MikePopoloski** [comment]
Yes, that's right. Patches are definitely welcome.

**Comment by martinda** [comment]
Some circles call them "manifest files".

**Comment by MikePopoloski** [comment]
Some notes on this since my original comment is conspicuously blank:
* The file should ideally accept basically any command line option, not just file lists
* File should support comments and possibly some primitive form of include directive
* This is most useful when paired with #360 so that entries in the file would be portable from other tools

**Comment by MikePopoloski** [comment]
Support for -f and -F command files have been added.
