### ISSUE TITLE
a bug in name upward lookup 

### ISSUE THREAD

**Issue by Winging** [MikePopoloski/slang#371]
```
module A();
  B #(7) b1();
  B #(11) b2();
endmodule

module B();
  parameter w = 10;
  var integer i;
  C c1();
endmodule

module C();
  initial $display(B.i, B.w);
endmodule


module top();
  A a1();
endmodule
```
xcelium> run
          x          7
          x         11
xmsim: *W,RNQUIE: Simulation is complete.
```

https://github.com/MikePopoloski/slang/blob/c20f4c213dc31a4c0f9927de97321884c4d32ffe/source/symbols/Lookup.cpp#L376
```
                symbol = nullptr;
                for (auto& instance : scope->membersOfType<InstanceSymbol>()) {
                    if (instance.getDefinition().name == name.text()) {
                        if (!symbol)
                            symbol = &instance;
                        else {
                            // TODO: error
                        }
                    }
                }
```
The lookup method here may always refer to the first instance b1. and Actually it should not raise issue if there is multi instance.
we may need to it when we get the parent instance and compare its definition with the name.

**Comment by MikePopoloski** [comment]
Thanks, should be fixed now.
