### ISSUE TITLE
parsing problem in property_expr

### ISSUE THREAD

**Issue by jankcorn** [MikePopoloski/slang#393]
First, thanks for the parser support for property/sequence exprs!

The statement:
     assert property (@(posedge dif_clk) ((dif_req) and dif_req) ##0 dif_gnt2);
gives a syntax error.  
I believe that it _might_ be caused by the fact that both
    '( property_expr )' and '( sequence_expr )' are valid token strings 
(the error goes away if the parens around '(dif_req)' are deleted.

**Comment by MikePopoloski** [comment]
Yeah, unfortunately you can't know if a parenthesized expression is a normal, sequence, or property expression without infinite lookahead so I do a fixup approach, but it's clearly still buggy. I'll look at it more.

**Comment by jankcorn** [comment]
Thanks!

**Comment by MikePopoloski** [comment]
Fixed in cbf7ea8966841866dc7a7ae3fad51e538f86cd22

**Comment by jankcorn** [comment]
Thanks very much!
