### ISSUE TITLE
ambiguity in JSON for property_expr with implication

### ISSUE THREAD

**Issue by jankcorn** [MikePopoloski/slang#395]
It appears that an identical JSON is generated for:
    a |-> b
and
    a |=> b
Do you eventually intend to keep these distinct in the JSON or are you planning to put the LRM rewrite rule 'F.3.4.3.3 Derived nonoverlapping implication operator' into the parser?
 For example:
       a |=> b
becomes
       a ##1  1 |-> b

Thanks!

**Comment by MikePopoloski** [comment]
I'll add an enum. I'm only planning to do the parts of the rewrite algorithm that are needed to expand out sequence and property instances and to enforce all semantic rules. The rest seems like it should be deferred until simulation.

**Comment by jankcorn** [comment]
Yes, I was planning on doing the rewrite in my code (downstream from slang).

Thanks for adding the enum!

**Comment by MikePopoloski** [comment]
Fixed in 4981a18f
