### ISSUE TITLE
Add support for .f filelists

### ISSUE THREAD

**Issue by DeeeeLAN** [MikePopoloski/slang#424]
I know they aren't an official feature of the language but since a lot of the major simulators support them anyway, it would be nice to have for compatibility purposes. All of my projects have used them so it would be nice to leverage the preexisting files instead of rebuilding a file list in a new format.

**Comment by MikePopoloski** [comment]
I agree, though I already have #361 to track this so I'm going to close this issue in favor of the older one.

**Comment by DeeeeLAN** [comment]
Thanks. I tried searching but none of my keywords hit that particular ticket.
