### ISSUE TITLE
hierarchy bind give error message 

### ISSUE THREAD

**Issue by aegean0228** [MikePopoloski/slang#426]
module Top();
    Child child1();
    Child child2();
    bind Top.child1 Sub #(1)inst();
    bind Top.child2 Sub #(2)inst();
endmodule
   module Child();
    endmodule

module Sub();
    parameter P = 0;
endmodule

this should be a valid case, but i saw redefinition error

**Comment by MikePopoloski** [comment]
Thanks for the report. Support for bind directives is not yet complete. Closing this in favor of the other issue already tracking it: #353
