### ISSUE TITLE
module bind doesn't work

### ISSUE THREAD

**Issue by aegean0228** [MikePopoloski/slang#427]
module Top();
    Child child1();
    Child child2();
    bind Child Sub #(1)inst();
endmodule
   module Child();
    endmodule

module Sub();
    parameter P = 0;
endmodule

i didn't see the bind works

**Comment by MikePopoloski** [comment]
Thanks for the report. Support for the bind directive is not yet complete. I'm going to close this in favor of the other issue already tracking its development: #353
