### ISSUE TITLE
upward hierarchy reference in defparam give wrong result 

### ISSUE THREAD

**Issue by aegean0228** [MikePopoloski/slang#429]
module Top();
    dut_0  inst_0();
    dut_1  inst_1();
endmodule

module dut_0();
    dut inst_dut();
    dummy inst_dummy();
endmodule

module dut_1();
    dut inst_dut();
    dummy inst_dummy();
endmodule

module dummy();
parameter P = 0;
endmodule

module dut();
    parameter P = 0;
    sub inst();
endmodule

module sub();
    defparam inst_dummy.P = 100;
endmodule

both Top.inst_0.inst_dummy.P and Top.inst_1.inst_dummy.P should equal 100,
but i saw Top.inst_1.inst_dummy.P = 0 which is wrong

**Comment by MikePopoloski** [comment]
Thanks for the report. Support for defparams is not yet complete; closing this in favor of the other issue already tracking it: #383
