### ISSUE TITLE
Question: How can I insert a node to an empty SyntaxList with SyntaxRewriter?

### ISSUE THREAD

**Issue by mytbk** [MikePopoloski/slang#476]
I want to insert some statements to a class method. I use the following in the SyntaxRewriter:

```
void handle(const slang::ClassMethodDeclarationSyntax &decl)
{
    ...
    insertBefore(*decl.declaration->items[0], parse(...));
}
```

However, if ``decl.declaration->items`` is an empty SyntaxList, the program will crash when using this.

I also try to replace the SyntaxList, but the program crashes when printing the nodes. Using insertBefore on it doesn't work either.

**Comment by MikePopoloski** [comment]
I kind of expect replacing the SyntaxList with another list to work, though it might be unwieldy to form such a list. However, I think there should probably be another set of helper methods to insert a new kind of change, insertAtFront and insertAtBack, which would take a list directly and not a specific node within a list. That way it wouldn't matter to you whether the list was empty or not when adding an item to it.
