### ISSUE TITLE
Check json output for simple example, seems to omit rand modifier. 

### ISSUE THREAD

**Issue by Practical-UVM-Step-By-Step** [MikePopoloski/slang#500]
HI:
I just started experimenting with your code, and was hoping you could tell me if the JSON output was correct.
Here is a small test case.  I was hoping the json output did have some information that there was a rand modifier for variables I and j in the code below. Maybe I am not looking at it right or is it a bug?  I just tried the code on GitHub after building it. 
Thanks!
Example:
...
module top;
  
class myclass;
        rand local int i;
        rand protected int k;
        string s;

        constraint c {
                i < 10;
                i > 6;
                k < 100; k > 0;

        }

        function new();
                s = "hello";
        endfunction

        function displayme();
                $display("the value of i and k are %d %d",i,k);
        endfunction
endclass

myclass cl;

initial begin
        cl = new;
        end
endmodule
...

**Comment by MikePopoloski** [comment]
It was missing; I added it in bf302480b05cd811d31821e9fc4bf9c372a677fb
