### ISSUE TITLE
exp suffix lexed into hex_number token

### ISSUE THREAD

**Issue by mytbk** [MikePopoloski/slang#501]
In #498, ``foo(32'h0e+32'h4000)`` is printed as ``foo(32'h0e+32+32'h4000)`` after the fix. I tried to debug the lexer, and find Lexer::lexToken() returns the tokens ``foo``, ``(``, ``32``, ``'h``, ``0e+32``, ... I think it's caused by the handling of 'e', where the lexer treats ``0e+32`` a real number. However, when there's ``32'h`` prefix, the letter e should be the hex digit. The comment at source/parsing/Lexer.cpp:803 also mentions this.

_Originally posted by @mytbk in https://github.com/MikePopoloski/slang/issues/498#issuecomment-975019979_

**Comment by MikePopoloski** [comment]
Thanks, follow up fix is in cb971ea604d06579b8ebf534addee6c0a316f7e0
