### ISSUE TITLE
Add better path support for include files

### ISSUE THREAD

**Issue by DeeeeLAN** [MikePopoloski/slang#507]
Copied from our conversation:

> There are probably a few decent options. One option would be to just resolve every relative path so it using the full system path, then every path would be standardized. This would probably be the simplest option to go with. Another option would be to provide some sort of access to the map so I can either manually override the buffer a path points to, or at least see what paths are used for the keys and I could copy the key into the assignText call to make sure it matches. But overriding the buffer directly is probably a bad idea at the moment since there is no support for changing the comp unit in this matter. I imagine that will be a bigger task but that would be nice to have eventually, being able to take a source manager or compilation unit, and either changing a file or creating a new sm/comp with one or more files swapped out or deleted.

> As you can imagine, the typical flow is going to be to load a new compilation object each time a user edits a file, load in all the files that have not changed, and load in the text for the file currently being edited, so the most recent changes are represented. The language server client provides the path to the file, but it is either a full path, or at least relative to the root of the project, which will typically not match up with the `include directives inside a pkg in the project.

> And maybe when processing includes, it can attempt to add the directory for the files to the source manager, perhaps checking if it exists beforehand. It already issues errors if it can't find the file so I imagine this would be relatively safe. It sounds like that already happens for buffers loaded from file but if it is loaded from text it isn't doing this, even if the buffer has a "path" associated with it through the assignText function. I guess if there is no path assigned, it wouldn't know how to resolve the path, which makes sense. Perhaps a separate warning could be provided in this situation? Not sure.

**Comment by MikePopoloski** [comment]
I reworked how include path handling is done for in-memory text buffers. I think it should probably work as you expect now.

**Comment by DeeeeLAN** [comment]
Awesome, I will give it a try and see if it does the job I am hoping it will do. Not sure when I will get to it.
