### ISSUE TITLE
sv-lang explorer page does not seem to be working again

### ISSUE THREAD

**Issue by githubexplorer2** [MikePopoloski/slang#545]
The page at: 
[https://sv-lang.com/explore/#](https://sv-lang.com/explore/#)

Does not appear to work again.

I get a static set of output in the compiler tab: 
"/slangbin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /slangbin)
/slangbin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /slangbin)
/slangbin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /slangbin)
/slangbin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /slangbin)
/slangbin: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /slangbin)

compiler returned: 1"

It also seems not to have any controls to add or reload any of the tabs (not sure if those ought to exist as this is my first time visiting the page).

Thank you in advance!

**Comment by MikePopoloski** [comment]
Thanks for the report. This has been fixed.

You're not missing anything on the page, it's pretty bare-bones right now.
