### ISSUE TITLE
Slang explorer unable to show output

### ISSUE THREAD

**Issue by githubexplorer2** [MikePopoloski/slang#546]
Hi,

When I enter code into the page at:
https://sv-lang.com/explore/#

I am unable to see my output from calls to $display, $monitor or other built-in SystemVerilog functions. Is this the desired behavior? I thought that the purpose for the tool being able to identify the top-level test bench module is to actually compile and “run” at least the initial blocks of this tb module.
Do I need to name the top level test bench something special in order for it to run?

Thank you

**Comment by MikePopoloski** [comment]
slang is not a simulator (at least not yet) -- it performs compilation, elaboration, and linting. It would be nice for it to run simulations some day though.
