### ISSUE TITLE
Backwards range for dist constraint is never selected in simulation

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#563]
The below example has an illegal range in a distribution constraint.   VCS flags no warning or error but I have observed in simulation that it will never choose values of 1:15 for this case.  Questa explicitly flags a warning that the range is backwards and won't be selected.

I'm still hunting for LRM language (searching for "range" has a lot of hits), but based on VCS and Questa results, this case really seems like it should be a hard-error for Slang.

```systemverilog
class C;
    rand bit [4:0] a;

    constraint a_c {
        a dist { 16 :/ 1, [15:1] :/ 1};
    }
endclass
```

**Comment by MikePopoloski** [comment]
I didn't find anything in the LRM about this but it's pretty straightforward to add a warning for it -- added in c1743464418993a939eecff3824839653c2c373e
