### ISSUE TITLE
Native support for UPF package during compile (IEEE 1801-2013)

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#573]
I'm running into code in projects that assumes tools have support for the UPF specification, and the code has "import UPF::*;" and then reference the types and routines from that package.   VCS and Questa support this package in a provided library via -liblist UPF and -L mtiUPF respectively.

It does appear that a 'stub' definition of the package is in the IEEE 1801-2013 spec (Annex B.4), so I can add that stub to the filelist to avoid analyze errors on undefined packages/types.  But I thought I'd open this issue to see if you have a preference for native support of the UPF package in Slang vs leaving it external.   Progressing beyond the stub wouldn't come into play until simulation support is in the picture.

**Comment by MikePopoloski** [comment]
I wouldn't mind eventually shipping it alongside slang but it would be as a standalone file, i.e. not built into the compiler binary, so I don't see a lot of benefit to trying to do that right now. You might as well continue on with the stub until it makes more sense to look at including it in the slang distribution.
