### ISSUE TITLE
Expression should be non copiable

### ISSUE THREAD

**Issue by Sustrak** [MikePopoloski/slang#642]
**Describe the bug**
Getting a copy from an Expression object or derived type may lead to a segmentation fault, when accessing some of the Expression members.

**To Reproduce**
```c++
    struct CollectLHSIdentifiers : public ASTVisitor<CollectLHSIdentifiers, true, true> {
        void handle(const AssignmentExpression& assignment) {
            if (auto named_value = assignment.left(); named_value.kind == slang::ExpressionKind::NamedValue) {
                auto name = named_value.as<NamedValueExpression>();
                std::cout << name.symbol.name << std::endl;
            }
        }

```

This AST Visitor might throw a segmentation fault when accessing the `name.symbol.name` member. Since auto won't infer a reference, when getting the `assignment.left()` expression.

Even though this might be an error of the programmer it would be nice that the API don't let you take a copy of an Expression object by deleting the copy and assignment operator.  

**Proposed solution**
Add the following code to the Expresson class in `include/slang/binding/Expression.h`:
```c++
    Expression(const Expression&) = delete;
    Expression& operator=(Expression&) = delete;
```

**Comment by MikePopoloski** [comment]
That's a good idea. Done in b8c183aedb6402285c095176fff014602091fcfd
