### ISSUE TITLE
support strength information in NetSymbol

### ISSUE THREAD

**Issue by marcelchangTW** [MikePopoloski/slang#664]
**Is your feature request related to a problem? Please describe.**
Hi,
    There is a trireq net type with charge strength 'large' as the following, I would like visit the symbol ast tree to get this information, but it seems not keep it in NetSymbol now. File a request here first, I will keep dig into source code. Thanks.

`trireg (large) logic #(0, 0, 0) capl;`

**Comment by MikePopoloski** [comment]
You're right, it looks like I missed adding this to the AST. I will do so.

**Comment by MikePopoloski** [comment]
This has been added.
