### ISSUE TITLE
 skip the analysis of IP during the analysis?

### ISSUE THREAD

**Issue by fzwwj95** [MikePopoloski/slang#731]
**Is your feature request related to a problem? Please describe.**
When I prase the design with slang, the IP nuclear I encountered will be recognized as the top layer. Where I instantiate the IP, the prase will report an error

**Describe the solution you'd like**
When I encountered an IP when I was parsing Slang, I either didn't parse it or printed out the IP name and told me it was an IP

**Comment by MikePopoloski** [comment]
I don't really understand what you're asking. Some of the modules that you instantiate in your code are from IP vendors and you want them to be printed out as IP modules? How would slang know which modules are supposed to be from your IP vendor?
