### ISSUE TITLE
fatal error: span: No such file or directory

### ISSUE THREAD

**Issue by fzwwj95** [MikePopoloski/slang#738]
Describe the bug
Doing:
 cmake --build build
Scanning dependencies of target fmt
[  1%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/format.cc.o
[  1%] Building CXX object _deps/fmt-build/CMakeFiles/fmt.dir/src/os.cc.o
[  2%] Linking CXX static library ../../lib/libfmt.a
[  2%] Built target fmt
[  2%] Generating diagnostics
[  3%] Generating syntax
Scanning dependencies of target slang_slang
[  3%] Building CXX object source/CMakeFiles/slang_slang.dir/AllSyntax.cpp.o
In file included from /mnt/e/ubuntu20.04/work/slang/source/../include/slang/util/BumpAllocator.h:12,
                 from /mnt/e/ubuntu20.04/work/slang/source/../include/slang/util/SmallVector.h:16,
                 from /mnt/e/ubuntu20.04/work/slang/source/../include/slang/numeric/SVInt.h:15,
                 from /mnt/e/ubuntu20.04/work/slang/source/../include/slang/parsing/Token.h:10,
                 from /mnt/e/ubuntu20.04/work/slang/build/source/slang/syntax/AllSyntax.h:10,
                 from /mnt/e/ubuntu20.04/work/slang/build/source/AllSyntax.cpp:8:
/mnt/e/ubuntu20.04/work/slang/source/../include/slang/util/Util.h:13:10: fatal error: span: No such file or directory
   13 | #include <span>
      |          ^~~~~~
compilation terminated.
make[2]: *** [source/CMakeFiles/slang_slang.dir/build.make:96: source/CMakeFiles/slang_slang.dir/AllSyntax.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1091: source/CMakeFiles/slang_slang.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Additional context

Ubuntu 22.04.2 LTS on WSL Win10

**Comment by MikePopoloski** [comment]
Are you building with a supported compiler? The minimum supported GCC and Clang is both version 10 (C++20 support is needed).
