### ISSUE TITLE
Parse of  dynamic bit width

### ISSUE THREAD

**Issue by fzwwj95** [MikePopoloski/slang#739]
**Describe the bug**
my systemverilog code: 
' logic a;
 assign a = 'b11;'
Here I use the dynamic bit width （‘b11），the width both signal a and 'b11 should be 2bits，but they are both 32bits in AST json parsed by slang. 
Signal a extends to 32 bits because ‘b11 is 32 bits，But why is  ‘b11 32bits？
Is there anything wrong?I am confused here.

**To Reproduce**
**code：**

' logic a;
 assign a = 'b11;'

**segment of AST json ：**

    "name": "",
    "kind": "ContinuousAssign",
    "addr": 94811850763520,
    "assignment": {
      "kind": "Assignment",
      "type": "logic",
      "left": {
        "kind": "NamedValue",
        "type": "logic",
        "symbol": "94811851236360 a"
      },
      "right": {
        "kind": "Conversion",
        "type": "logic",
        "operand": {
          "kind": "Conversion",
          "type": "logic[31:0]",
          "operand": {
            "kind": "IntegerLiteral",
            "type": "bit[31:0]",
            "value": "32'd3",
            "constant": "32'd3"
          },
          "constant": "32'd3"
        },

**Comment by MikePopoloski** [comment]
I think you are misunderstanding how unsized integer constants work in SystemVerilog; the LRM says this:
> The number of bits that make up an unsized number (which is a simple decimal number or a number with a
base specifier but no size specification) shall be at least 32.

Which is why if you run the following code on any of the big simulators:
```
module m;
  initial $display($typename('b11));
endmodule
```
You will most likely get the output:
```
bit[31:0]
```
or
```
logic[31:0]
```
