### ISSUE TITLE
input cmake --build build in Ubuntu occurred error 

### ISSUE THREAD

**Issue by jrainzzz** [MikePopoloski/slang#764]
**Describe the bug**
/home/zhang/slang/slang/source/ast/Statements.cpp:1597:46:   required from here
/usr/include/c++/10/bits/stl_uninitialized.h:137:72: error: static assertion failed: result type must be constructible from value type of input range
  137 | static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,

make[2]: *** [source/CMakeFiles/slang_slang.dir/build.make:1396：source/CMakeFiles/slang_slang.dir/ast/Statements.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1078：source/CMakeFiles/slang_slang.dir/all] 错误 2
make: *** [Makefile:163：all] 错误 2

How should I solve this problem？
thanks！

![image](https://github.com/MikePopoloski/slang/assets/113433494/98d78243-abb6-4d72-989a-905157c39e1c)

**Comment by MikePopoloski** [comment]
Closing this for now. Feel free to reopen if you want to add more information.

**Comment by jrainzzz** [comment]
ok,i will add more information tomorrow,thanks




&nbsp;


Mr。Zhang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Michael ***@***.***&gt;; 
发送时间: 2023年6月1日(星期四) 凌晨2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MikePopoloski/slang] input cmake --build build in Ubuntu occurred error  (Issue #764)





 
Closing this for now. Feel free to reopen if you want to add more information.

**Comment by jrainzzz** [comment]
![image](https://github.com/MikePopoloski/slang/assets/113433494/357ef3da-df3f-4122-ac04-0e2272fc1ba5)
![image](https://github.com/MikePopoloski/slang/assets/113433494/686df1af-e779-407c-a8ef-f1c073153b7d)
![image](https://github.com/MikePopoloski/slang/assets/113433494/7b01731c-0a7a-412b-a12c-732857c57bf7)
![image](https://github.com/MikePopoloski/slang/assets/113433494/adaeba9d-11e1-4e55-8957-16216b1f9d31)
### then i continued to input commands.(cmake --build build)
![image](https://github.com/MikePopoloski/slang/assets/113433494/a13b6ef7-ae1e-44af-b954-2c2ab7efb8bc)
### Then, when running to 79%, there was an error message when building Statements. cpp. o
![image](https://github.com/MikePopoloski/slang/assets/113433494/cfbfebfc-776b-4c2a-a9e0-0f608b54c7f5)
![image](https://github.com/MikePopoloski/slang/assets/113433494/f67655c6-d164-42a6-beec-2fb64d3d4006)
[error_message.txt](https://github.com/MikePopoloski/slang/files/11621743/error_message.txt)

**Comment by MikePopoloski** [comment]
Hmm, weird. I can build without issue with an almost identical setup. The only difference I can see is that my system has GCC 10.4.0 whereas you have 10.3.0. There's no straightforward way for me to downgrade, can you upgrade your GCC install and see if that fixes the issue?

**Comment by jrainzzz** [comment]
I upgraded the gcc version to 10.4 but still encountered the same error

**Comment by MikePopoloski** [comment]
Since there's been no updates I'm going to close this. Feel free to reopen if you have additional information we can use to debug.
