### ISSUE TITLE
RFC: expose visitors to python

### ISSUE THREAD

**Issue by tdp2110** [MikePopoloski/slang#765]
**Is your feature request related to a problem? Please describe.**
Expose visitor pattern to python for richness of pybindings.

**Describe the solution you'd like**
Given a `pyslang.Expression`, `pyslang.Statement`, or `pyslang.Symbol`, `t`, and a python object `f`, 
expose a function
```
  t.visit(f)
```
to recursively visit `t`. To emulate the `handle` pattern used in C++, something closer to the [MLIR walk pattern](https://github.com/MikePopoloski/slang/compare/master...tdp2110:slang:py-visitors?expand=1) could be used, for example:

```
def visit_fn(n):
   if isinstance(n, pyslang.NamedValueExpression):
    # "handle" a NVE
   if isinstance(n, pyslang.BinaryExpression):
     # "handle" a binary Exp
  if should_continue:
    return pyslang.Continue # continue traversing in pre-order
  return pyslang.Skip # skip children

v.visit(visit_fn)
```

A basic sample implementation is available [here](https://github.com/MikePopoloski/slang/compare/master...tdp2110:slang:py-visitors?expand=1), which doesn't fully implement the continue/skip pattern as above -- only using the noneness of the return value.

**Describe alternatives you've considered**
Re-implement the visitor pattern in pure python (error prone and likely incomplete).

I would find this useful. If you like the idea, I'd be happy to flush it out and submit a PR.

**Comment by MikePopoloski** [comment]
Sure, this makes sense to me. Happy to take a PR.
