### ISSUE TITLE
Mux in netlist path

### ISSUE THREAD

**Issue by renau** [MikePopoloski/slang#779]
**Describe the bug**

The variables in the if/else are not used in the  netlist.

**To Reproduce**

The following module generates a dot file (slang-netlist) where the `sel` is not used for the `mux.f` but clearly the mux selector is part of the sources.

```
module mux(input a, input b, input sel, output reg f);

always @(*) begin
  if (sel == 1'b0) begin
    f = a;
  end else begin
    f = b;
  end
end

endmodule
```

**Comment by MikePopoloski** [comment]
@jameshanlon

**Comment by jameshanlon** [comment]
I'll take a look at this. The problem is that dependencies are not propagated from the variables appearing in the condition to the ones they control (ie the targets of any assignments). I should also add a note to the `slang-netlist` readme that the tool is currently a work in progress!
