### ISSUE TITLE
AST generation and compatibility with Prettier plugin

### ISSUE THREAD

**Issue by gustcar** [MikePopoloski/slang#791]
Hi! Can this parser be used to add the SystemVerilog language to the Prettier Code Formatter plugin? It would be nice to have it in Prettier to have a standardized code across the project.

https://prettier.io

Thank you!

**Comment by MikePopoloski** [comment]
I'm not familiar with Prettier. It seems like it all needs to be in Javascript? If you can shell out to another tool then sure, slang could be used for this. You'll need to ask the Prettier team or create your own plugin or however it works though, it's not something I can do for you.
