### ISSUE TITLE
Implement __FILE__ and __LINE__ macros

### ISSUE THREAD

**Issue by MikePopoloski** [MikePopoloski/slang#8]
The intrinsic __FILE__ and __LINE__ macros are currently recognized but generate empty tokens ("" and 0 respectively). The __LINE__ macro in particular will require making use of the source manager infrastructure for figuring out which line we're looking at.

Note that this plays into the `line directive as well, which changes the "apparent" line number (like #line in C++).

**Comment by drsam94** [comment]
This issue was closed by commit 0649d61
