### ISSUE TITLE
Make slang available on ConanCenter

### ISSUE THREAD

**Issue by learningstud** [MikePopoloski/slang#833]
**Is your feature request related to a problem? Please describe.**
For mere convenience.

**Describe the solution you'd like**
Make slang available on ConanCenter.

**Describe alternatives you've considered**
As suggested by the manual: fetch the source, build the source, and install system wide.

**Additional context**
No.

**Comment by MikePopoloski** [comment]
I think this is probably an issue for https://github.com/conan-io/conan-center-index -- if you need fixes from me to make it smoother / easier I'm happy to help but I expect it should be straightforward already.

**Comment by learningstud** [comment]
Yes, thanks for pointing out my erroneous attribution of liability. I have opened an issue at conan-center-index.
