### ISSUE TITLE
Line number in syntax tree

### ISSUE THREAD

**Issue by riggy2013** [MikePopoloski/slang#837]
Sorry, this is not a bug, maybe not a feature request either.

I am using pyslang to parse Systemverilog code and working with certain structure in the RTL code, for example, extract all instance names. (instance name is at tree.root.members[0].members[#].instances[0].decl.name.value)

I wonder when I get the structure, where can I get the line number?

Thanks,

riggy2013

**Comment by MikePopoloski** [comment]
The SourceLocation type (accessible from a token with `.location()`) can be used to find the line number by using the SourceManager's getLineNumber function.

**Comment by riggy2013** [comment]
Here is sample code:

```
inst = tree.root.members[0].members[#].instances[0] #-- SyntaxNode(SyntaxKind.HierarchicalInstance)
tok = inst.getFirstToken() #--Token(TokenKind.Identifier)
sm = pyslang.SourceManager
ln = sm.getLineNumber(tok.location)
```

Above code will generate error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: getLineNumber(): incompatible function arguments. The following argument types are supported:
    1. (self: pyslang.SourceManager, location: pyslang.SourceLocation) -> int

Invoked with: SourceLocation(1, 75862)
```

**Comment by MikePopoloski** [comment]
You need `sm = pyslang.SourceManager()` with the parenthesis. Otherwise I think you're just getting an alias for the pybind11 type name.

**Comment by MikePopoloski** [comment]
Although actually I should be clear that you should actually be using the source manager that was used to parse the syntax tree (something like `tree.sourceManager`), otherwise it's not going to work correctly anyway.

**Comment by riggy2013** [comment]
Below code works:

```
sm = tree.getDefaultSourceManager()
inst = tree.root.members[0].members[#].instances[0] #-- SyntaxNode(SyntaxKind.HierarchicalInstance)
tok = inst.getFirstToken() #--Token(TokenKind.Identifier)
ln = sm.getLineNumber(tok.location)
```

Thanks a lot, Mike.
