### ISSUE TITLE
Q - Is there a way for pyslang to trim, add, and modify the AST (Abstract Syntax Tree)?

### ISSUE THREAD

**Issue by darcy-wu** [MikePopoloski/slang#851]
thank you

**Comment by MikePopoloski** [comment]
No, the API exposed to Python is mostly read-only right now. It would be possible to expose more of the API but it would be a fair amount of effort. Probably easier in the long run to write such a tool using the C++ API instead.

**Comment by MikePopoloski** [comment]
Going to close this issue as it is now answered. If you have questions in the future (as opposed to an actual issue) feel free to open a Discussion instead.
