### ISSUE TITLE
Q - Can pyslang perform constant folding on expressions?

### ISSUE THREAD

**Issue by darcy-wu** [MikePopoloski/slang#852]
It would be great if you could provide an example. Thank you!

**Comment by MikePopoloski** [comment]
Yes, it can. Expression objects have an eval() method that you can call to try to evaluate them.

**Comment by MikePopoloski** [comment]
Going to close this issue as it is now answered. If you have questions in the future (as opposed to an actual issue) feel free to open a Discussion instead.
