### ISSUE TITLE
Wrong name returned for tidy checker.

### ISSUE THREAD

**Issue by Krym4s** [MikePopoloski/slang#854]
This tidy checker returns name of another checker ("AlwaysCombNonBlocking"), this should return "AlwaysFFBlocking", isn't it?

https://github.com/MikePopoloski/slang/blob/52ee547b665fe7b8974a8f7e66de7c37beef4aae/tools/tidy/src/style/AlwaysFFBlocking.cpp#L64C63-L64C63

**Comment by MikePopoloski** [comment]
Yes, looks like a typo.

**Comment by Sustrak** [comment]
#857 should fix this
