### ISSUE TITLE
Nested Module Definition Not Reflected in slang --ast-json Output

### ISSUE THREAD

**Issue by yanggeorge** [MikePopoloski/slang#863]
**Is your feature request related to a problem? Please describe.**
I've encountered a problem when using the slang tool to compile and analyze SystemVerilog code with nested modules. Specifically, after compiling the following SystemVerilog code and using the slang --ast-json command to inspect the Abstract Syntax Tree (AST), I noticed that the AST representation does not seem to include the nested TestModule definition within the testModule's scope.
```systemverilog
module top(input logic CLK, output logic RST);

    module nested(input logic CLK, output logic RST);
    endmodule

endmodule
```

**Describe the solution you'd like**
I would like the slang --ast-json output to accurately reflect the nested module structure, showing the TestModule as part of the testModule's scope. Ideally, the AST should provide a clear and hierarchical representation of all module definitions, including nested modules, to facilitate better analysis and understanding of the code structure.

**Describe alternatives you've considered**
As an alternative, I've considered manually parsing the SystemVerilog code to track nested modules, but this approach is prone to errors and does not leverage the powerful analysis capabilities of slang. Another alternative might be using a different tool for AST generation, but I prefer to understand if slang can be enhanced or if I'm missing something in its current functionality.

**Additional context**
Below is the JSON output from the slang --ast-json command after compiling the provided SystemVerilog code. As you can see, the testModule's scope includes ports and internal variables but does not contain the nested TestModule definition. Understanding why the nested module's definition is not included in the AST representation is crucial for comprehensive analysis of complex SystemVerilog designs.
```json
{
  "name": "$root",
  "kind": "Root",
  "addr": 2199023598400,
  "members": [
    {
      "name": "",
      "kind": "CompilationUnit",
      "addr": 2199025895968
    },
    {
      "name": "top",
      "kind": "Instance",
      "addr": 2199025897856,
      "body": {
        "name": "top",
        "kind": "InstanceBody",
        "addr": 2199025897488,
        "members": [
          {
            "name": "CLK",
            "kind": "Port",
            "addr": 2199025897992,
            "type": "logic",
            "direction": "In",
            "internalSymbol": "2199025898168 CLK"
          },
          {
            "name": "CLK",
            "kind": "Variable",
            "addr": 2199025898168,
            "type": "logic",
            "lifetime": "Static"
          },
          {
            "name": "RST",
            "kind": "Port",
            "addr": 2199025898544,
            "type": "logic",
            "direction": "Out",
            "internalSymbol": "2199025898720 RST"
          },
          {
            "name": "RST",
            "kind": "Variable",
            "addr": 2199025898720,
            "type": "logic",
            "lifetime": "Static"
          }
        ],
        "definition": "top"
      },
      "connections": [
      ]
    }
  ]
}
```
Thank you for your time and assistance.
Best regards

**Comment by yanggeorge** [comment]
In slang, Definition class does not inherit from Symbol. And Scope.members() is only about symbols. So I cannot from members to find nested Definitions. 

But I find every definition has ref to a scope. It seems that the only way to find hierarchical relationship is to traverse the definitionMemory in compiltion instanse.

Why Scope class cannot contain a vector of definitions?

**Comment by MikePopoloski** [comment]
The AST only includes *instances*, not definitions themselves. This is because the AST is supposed to represent the elaborated design tree, and a definition that is not instantiated is not part of the elaborated design tree. If you were to instantiate that nested module you should see it in the output.

**Comment by yanggeorge** [comment]
@MikePopoloski  Thanks for your reply. I have got that AST don't include the unused definitions.

So It is hard to write a tidy check on all definitions, since Compilation class don't give such API  to access them.

**Comment by MikePopoloski** [comment]
It wouldn't be that hard to add such an API to the Compilation, since it has that info internally. I can do that.

**Comment by yanggeorge** [comment]
Thank you. I wish that it would not make conflict to your API design.

**Comment by MikePopoloski** [comment]
Added in 05e147efa7c787d0e1c09049214b80076048c1b6
