### ISSUE TITLE
Output of exists() method for associative arrays not treated as int type?

### ISSUE THREAD

**Issue by jrudess** [MikePopoloski/slang#909]
I was expecting -Wint-bool-conv to flag a warning for this example.  LRM section is 7.9.3.   All the other built-in methods that return int type do appear to be flagged by the warning.

```systemverilog
class C;
    bit m[string];

    function f();
        if (m.exists("test")) begin
        end
    endfunction

endclass
```

**Comment by jrudess** [comment]
Read through the code in ArrayMethods.cpp and it looks like this is intentional behavior (i.e. getEffectiveWidth returns 1).

**Comment by MikePopoloski** [comment]
Yeah, a warning here seems to serve no purpose but to annoy people, since the result is essentially Boolean.
