### ISSUE TITLE
Let slang ignore backslashes at the end of lines in a -f file

### ISSUE THREAD

**Issue by udif** [MikePopoloski/slang#964]
**Describe the bug**
I don't know if I should define this as a bug or a feature request, but here it goes...

**To Reproduce**
put backslashes at the end of each line on your `-f` file, and see `slang` complaining.

**Describe the solution you'd like**
Many linux tools (mostly shells) requires you to put backslash at the end of the line if you want it to be considered as one long line.
Out of habit, I put backslashes on some of my `-f` file used by one of the big tool vendors.
Apparently it worked fine, because the tool didn't complain, and it kind of made sense since putting arguments in a `-f` file is replacing command line args which naturally needs to be on on line.  
When I tried the same file with `slang` it failed miserably.

This change is small, and would be welcomed if only for the fact that other tools accept it, and it's not violating any standard by doing this. I haven't done any PR yet because I wanted to see first what do you think of such a change.

**Comment by MikePopoloski** [comment]
Sure, seems straightforward to me.
