### ISSUE TITLE
slang does not accept DPI task calls without parentheses

### ISSUE THREAD

**Issue by udif** [MikePopoloski/slang#971]
**Describe the bug**
slang seems to allow calling tasks without parentheses if they have no inputs, but does not allow so for DPI tasks.

**To Reproduce**
The following code yields an error:
```
module t;
task task1;
endtask
import "DPI-C" context task dpi_init;

initial begin
  dpi_init;
  task1;
end
endmodule
```

**Comment by MikePopoloski** [comment]
Fixed in 755e968996a642f258ed944979700783e0d27a2b
