### ISSUE TITLE
Add unused import check

### ISSUE THREAD

**Issue by corco** [MikePopoloski/slang#974]
Given the following code

```systemverilog
package pkg;

  localparam int A = 12;

endpackage : pkg

module mod;

  import pkg::A;

endmodule : mod
```

I would like to get a warning that "unused import pkg::A". It could be added with "-Wunused-import" and be included in "-Wunused".

**Comment by MikePopoloski** [comment]
Added in e342f51565c8869b60847ee734b9808f027d286f
